### ISSUE TITLE
Could not close the serial port.

### ISSUE THREAD

**Issue by SheddingNeurology** [xclud/dart_serial#2]
Could not close the serial port.

**Comment by iKK001** [comment]
Same here, cannot close the serial port !!

Any solution to this ?

Your Example leads to the following error when trying to close the port :

```
TypeError: Failed to execute 'close' on 'SerialPort': Cannot cancel a locked stream
```

**Comment by xclud** [comment]
This should have been fixed in `0.0.7`.

**Comment by wreyford** [comment]
I was excited to see the many changes, but unfortunately still getting the error:
`TypeError: Failed to execute 'close' on 'SerialPort': Cannot cancel a locked stream`
We still cannot close the serial port properly. This is a long term shortcoming, and hopefully can be fixed.

**Comment by xclud** [comment]
@wreyford The example seems to be working (at least on my side, Windows 11 & Chrome latest version).

Please take a look at https://serial.pwa.ir

**Comment by wreyford** [comment]
@xclud Thanks for your reply. I took your home_page.dart code and included as is in my code.

I ran into the same error I was initially getting when testing with your code:
`TypeError: Failed to execute 'read' on 'ReadableStreamDefaultReader': This readable stream reader has been released and cannot be used to read from its previous owner stream`
I get this error in a continuous loop, and have to cancel the app.

The only way I could resolve it using your exact example->home_page.dart, was to comment out the `reader.releaseLock();`
as follows
```
} catch (e) {
          if (kDebugMode) {
            print(e);
          }
        } finally {
          // reader.releaseLock();
        }
```
After that I could scan in RFID tags, and your code works, concerning the issue of not being able to close the port.
I reviewed my code, and noticed that I had left out '_reader = reader' in the beginning of the _startReceiving code:
```
_reader = reader;

      while (_keepReading) {
        try {
          final result = await reader.read().toDart;
```
When adding that back, to my code, I can now happily **confirm that it works as intended!**

Sorry for the false alarm. 
I am using Windows10, and it works both in Chrome and Edge. 

Perhaps you can explain why I'm getting the error mentioned in the beginning when using your exact home_page.dart.

**Comment by xclud** [comment]
My intention on the example is to show how to read from the serial port. Maybe we can have a separate reader async function and add everything read to a buffer and later consume from that buffer in another async function.

There are two things clear:

- You should `releaseLock` before closing the port.
- Once `releaseLock`ed, you cannot read from the port anymore.
